// Generated by CoffeeScript 1.6.3
(function() {
  var ReplrServer, ReplrWorkerPassthrough, funcs, repl;

  repl = require('repl');

  ReplrServer = require('./ReplrServer');

  ReplrWorkerPassthrough = require('./ReplrWorkerPassthrough');

  funcs = {
    create: function(options) {
      return new ReplrServer(options);
    },
    configureAsWorker: function(options) {
      return ReplrWorkerPassthrough.prototype.workerOptions = options;
    }
  };

  ReplrWorkerPassthrough.prototype.setup();

  module.exports = funcs;

}).call(this);
