// Generated by CoffeeScript 1.6.3
(function() {
  var Util;

  Util = (function() {
    function Util() {}

    return Util;

  })();

  Util.prototype.isInt = function(number) {
    var n, str;
    if (typeof number !== 'number') {
      return false;
    }
    str = String(number);
    n = ~~Number(str);
    return String(n) === str;
  };

  module.exports = Util;

}).call(this);
